Updates to shape_benchmark script
This commit provides the following updates to the shape_benchmark script:

  - Use Makefile to find benchmarks, so it can be run right after cmake
  - Compile benchmark files if not already in the directory
  - Do not regenerate data if available, only the figures
  - Make figures with absolute and relative running times
  - Do not try to produce plots if data file is empty
  - Tweak y-axis range to prevent legends from overlapping with data

diff --git a/scripts/shape_benchmark b/scripts/shape_benchmark
--- a/scripts/shape_benchmark
+++ b/scripts/shape_benchmark
@@ -2,8 +2,6 @@
 
 # USAGE:
 #
-# In the build directory (where all benchmarks are):
-#
 # NJOBS=10 NPOINTS=1024 shape_benchmark Box Cone ...
 #
 # If a list of shapes is not given, it attempts all shapes
@@ -17,26 +15,43 @@ if [[ $# > 0 ]]; then
 	SHAPES="$@"
 else
 	# attempt benchmark for all shapes
-	SHAPES=$(ls *Benchmark | xargs | sed -s 's/Benchmark//g')
+	SHAPES=$(grep Benchmark: Makefile | cut -d: -f1 | xargs | sed -s 's/Benchmark//g')
 fi
 
 for SHAPE in ${SHAPES}; do
-	# run benchmark for each shape
+	echo -ne "\r$(head -c 80 < /dev/zero | tr '\0' ' ')"
+	echo -ne "\rRunning Benchmark for ${SHAPE}"
+	# compile benchmark
+	[ -e ${SHAPE}Benchmark ] ||
+	(echo -e ": Compiling"; make ${SHAPE}Benchmark)
+
+	if [ $? != 0 ]; then
+		echo -e "--- FAILED ---"; sleep 1; continue
+	fi
+
+	readelf -h ${SHAPE}Benchmark | grep -q K1OM
+	if [ $? == 0 ]; then
+		TESTARCH="Intel (R) Xeon Phi(TM)"
+		TESTARCH="${TESTARCH} $(/opt/intel/mic/bin/micinfo -d 0 | grep SKU | awk '{print $NF}')"
+	else
+		TESTARCH="$(uname -p)"
+	fi
+
+	# generate data if needed
+	if [ ! -f ${SHAPE}.dat ]; then
+
+	# run benchmark
 	for i in $(seq -w 1 ${JOBS}); do
 		echo -ne "\rRunning Benchmark for ${SHAPE}: Job ${i}"
 		taskset -c $(($RANDOM % $(nproc))) \
 		readelf -h ${SHAPE}Benchmark | grep -q K1OM
 		if [ $? == 0 ]; then
-			TESTARCH="Intel (R) Xeon Phi(TM)"
-			TESTARCH="${TESTARCH} $(/opt/intel/mic/bin/micinfo -d 0 | grep SKU | awk '{print $NF}')"
 			ssh mic0 "(cd ${PWD}; ./${SHAPE}Benchmark -npoints ${NPTS})" &> ${SHAPE}-${i}.log
 		else
-			TESTARCH="$(uname -p)"
 			${SHAPE}Benchmark -npoints ${NPTS} &> ${SHAPE}-${i}.log
 		fi
 	done
-	echo
-	
+
 	# extract and process information from log files
 
 	# make data file header
@@ -48,7 +63,7 @@ for SHAPE in ${SHAPES}; do
 
 		# get running times from log files
 		for i in $(seq -w 1 ${JOBS}); do
-			grep -o "${FUNC}:[^\,]\+," ${SHAPE}-${i}.log | 
+			grep -o "${FUNC}:[^\,]\+," ${SHAPE}-${i}.log |
 			tr '()' '[]' | sed -e 's/-.-\+/0.0/g' |
 			sed 's/.*\[\([^]]*\)\].*/\1/g' |
 			tr -d s	| xargs >> ${SHAPE}-${FUNC}.dat
@@ -61,7 +76,7 @@ for SHAPE in ${SHAPES}; do
 				sum[i]   +=  \$i;
 				sumsq[i] += (\$i)^2
 			}
-		} 
+		}
 		END {
 			printf "${FUNC}\t"
 			for (i=1;i<=NF;i++) {
@@ -80,24 +95,34 @@ for SHAPE in ${SHAPES}; do
 		EOF
 	done
 
-	# generate plot using gnuplot (if it's available)
+	# remove temporary files
+	rm -f ${SHAPE}-*.{dat,log}
 
+	fi # [ ! -f ${SHAPE}.dat ]
+
+	# generate/update plot using gnuplot
 	if type -P gnuplot &>/dev/null; then
 		BACKEND="$(grep BACKEND CMakeCache.txt | cut -d= -f 2)"
 		PLOTCMD="plot '${SHAPE}.dat' u 2:xtic(1) t col"
+		PLOTREL="plot '${SHAPE}.dat' u (\$2/\$2):xtic(1) t col(2)"
 
-		for i in $(seq 3 `head -n 1 ${SHAPE}.dat | wc -w`); do
+		NCOLS=$(head -n 1 ${SHAPE}.dat | wc -w)
+
+		[ $NCOLS == 1 ] && continue # don't plot if data is bad
+
+		for i in $(seq 3 $NCOLS); do
 			PLOTCMD="${PLOTCMD}, '' u ${i} t col"
+			PLOTREL="${PLOTREL}, '' u (\$${i}/\$2) t col"
 		done
 
 		gnuplot -e "set term" | grep -q pdf
 
 		if [ $? == 0 ]; then
-			TERMOUTCMD="set term pdf color enh lw 1.2 size 8,6"
-			TERMOUTCMD="${TERMOUTCMD}; set output '${SHAPE}.pdf'"
+			FORMAT="pdf"
+			TERMCMD="set term pdf color enh lw 1.2 size 8,6"
 		else
-			TERMOUTCMD="set term png enh lw 1.2 size 1024,768"
-			TERMOUTCMD="${TERMOUTCMD}; set output '${SHAPE}.png'"
+			FORMAT="png"
+			TERMCMD="set term png enh lw 1.2 size 1024,768"
 		fi
 
 		gnuplot <<-EOF
@@ -110,11 +135,18 @@ for SHAPE in ${SHAPES}; do
 		set key top left maxrows 2
 		set title "${SHAPE} Benchmark — ${BACKEND} Backend — ${TESTARCH}"
 		set ylabel "Time (s)"
-		${TERMOUTCMD}; ${PLOTCMD}
+		${TERMCMD}; set output '/dev/null'; ${PLOTCMD}
+		set yrange [0:1.1*GPVAL_Y_MAX]
+		set output '${SHAPE}-abs.${FORMAT}'
+		${PLOTCMD}
+		unset yrange
+		set grid y
+		set ylabel "T / T_{vectorized}"
+		set output '/dev/null'; ${PLOTREL}
+		set yrange [0:1.1*GPVAL_Y_MAX]
+		set output '${SHAPE}-rel.${FORMAT}'
+		${PLOTREL}
 		EOF
 	fi
-
-	# remove temporary files
-
-	rm -f ${SHAPE}-*.{dat,log}
 done
+echo
